### ISSUE TITLE
Pricing formatting are diverse

### ISSUE THREAD

**Issue by GToidZ** [Sosokker/KU-Cafe#16]
(What I observed) Two of your menu has different pricing formatting. Please do come up with a standard formatting.

https://github.com/Sosokker/KU-Cafe/blob/d28a5651aca17a73455a0a0014dfa2291cb45261/menu.md?plain=1#L7-L14

https://github.com/Sosokker/KU-Cafe/blob/9a788d40bdc975540ca515c558e031b270129f91/menu.md?plain=1#L5-L12

**Comment by MeHappyLucky** [comment]
Thank you for reminding us, I have already tell the team to change our prices' format.

**Comment by GToidZ** [comment]
Issue is not yet resolved in the main branch. Please keep this open until you are clear that your work is completed.
